version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      dependency-name: ruff
      update-types: ["version-update:semver-minor"]
