version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: ruff
      update-types:
        # Ruff releases very frequently which results in
        # an annoying number of Dependabot PRs.
        - "version-update:semver-patch"
