sudo: false
matrix:
  include:
    - language: python
      python: "3.5"
      install: "pip install tox"
      script:
        - tox -e py35-lint
        - tox -e py35-test
    - language: python
      python: "3.6"
      install: "pip install tox"
      script:
        - tox -e py36-lint
        - tox -e py36-test
    - language: node_js
      install: "pip install tox"
      script:
        - npm install
        - make webpack-prod
      addons:
        apt:
          packages:
            - inkscape
            - icoutils
            - python-scour
            - optipng
