sudo: false
matrix:
  include:
    - language: python
      python: "3.5"
      install: "pip install tox"
      script:
        - tox -e py35-lint
        - tox -e py35-test
    - language: python
      python: "3.6"
      install: "pip install tox"
      script:
        - tox -e py36-lint
        - tox -e py36-test
    - language: python
      python: "3.7"
      dist: xenial
      sudo: true
      install: "sudo pip install tox"
      script:
        - tox -e py37-lint
        - tox -e py37-test
    - language: python
      python: "3.6"
      install:
        - "pip install tox"
        - "nvm install"
      script:
        - npm install
        - make webpack-prod
      addons:
        apt:
          packages:
            - inkscape
            - icoutils
            - python-scour
            - optipng
