os: linux
dist: xenial
language: python
branches:
  only:
    - master   # PRs
jobs:
  include:
    - name: "Test"
      python: "3.8"
      install: "sudo pip install tox"
      script:
        - tox -e lint
        - tox -e test
    - name: "Webpack Build"
      python: "3.8"
      install:
        - "sudo pip install tox"
        - "nvm install"
      script:
        - npm install
        - make webpack-release
      addons:
        apt:
          packages:
            - inkscape
            - icoutils
            - python-scour
            - optipng
