# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 01:47
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField()),
                ('fave', models.BooleanField()),
                ('author', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('guid', models.TextField(null=True)),
                ('raw_content', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('added', models.DateTimeField()),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('next_check', models.DateTimeField(null=True)),
                ('last_checked', models.DateTimeField(default=None, null=True)),
                ('last_updated', models.DateTimeField(default=None, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('etag', models.TextField(default=None, null=True)),
                ('last_modified', models.DateTimeField(default=None, null=True)),
                ('feed_title', models.TextField()),
                ('user_title', models.TextField(blank=True, default='')),
                ('site_url', models.URLField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True)),
                ('feeds', models.ManyToManyField(to='yarrharr.Feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='yarrharr.Feed'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('user', 'text')]),
        ),
    ]
