# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarrharr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='digest',
            field=models.BinaryField(default=None, max_length=32, null=True),
        ),
    ]
