# Generated by Django 4.0 on 2022-01-01 02:30

from django.db import migrations, models
import django.db.models.deletion

from ._0008_triggers import CREATE_TRIGGERS, DROP_TRIGGERS


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("yarrharr", "0002_url_help_text"),
    ]

    operations = [
        migrations.RunSQL(DROP_TRIGGERS, CREATE_TRIGGERS, elidable=True),
        migrations.AddField(
            model_name="feed",
            name="sort",
            field=models.CharField(
                choices=[("asc", "Ascending"), ("desc", "Descending")],
                default="desc",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="sort",
            field=models.CharField(
                choices=[("asc", "Ascending"), ("desc", "Descending")],
                default="desc",
                max_length=4,
            ),
        ),
        migrations.CreateModel(
            name="AllViewOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="desc",
                        max_length=4,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.user"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunSQL(CREATE_TRIGGERS, DROP_TRIGGERS, elidable=True),
    ]
