# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yarrharr", "0002_feed_digest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="digest",
            field=models.BinaryField(default=b"", max_length=32),
        ),
        migrations.AlterField(
            model_name="feed",
            name="etag",
            field=models.BinaryField(default=b"", max_length=1024),
        ),
        migrations.AlterField(
            model_name="feed",
            name="last_modified",
            field=models.BinaryField(default=b"", max_length=45),
        ),
    ]
