# Generated by Django 5.1.9 on 2025-05-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarrharr", "0003_feed_sort_label_sort_allviewoptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="content_length",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
