# Copyright © 2025 Tom Most <twm@freecog.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.2.6 on 2025-09-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarrharr", "0004_feed_content_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="last_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
