# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarrharr', '0004_non_null_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_rev',
            field=models.IntegerField(default=0),
        ),
    ]
