# Copyright © 2025 Tom Most <twm@freecog.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.2.6 on 2025-09-19 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yarrharr", "0005_feed_last_updated"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                UPDATE yarrharr_feed
                SET last_updated = (
                    SELECT MAX(date) FROM yarrharr_article
                    WHERE feed_id = yarrharr_feed.id
                )
                """
            ],
            reverse_sql=["UPDATE yarrharr_feed SET last_updated = NULL"],
        )
    ]
