# Generated by Django 5.2.6 on 2025-11-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yarrharr", "0007_feed_content_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="max_check_interval",
            field=models.DurationField(blank=True, default=None, null=True, verbose_name="Maximum check interval"),
        ),
        migrations.AddField(
            model_name="feed",
            name="min_check_interval",
            field=models.DurationField(blank=True, default=None, null=True, verbose_name="Minimum check interval"),
        ),
    ]
