# Generated by Django 5.2.8 on 2025-11-24 08:00

from django.db import migrations, models
from ._0008_triggers import CREATE_TRIGGERS, DROP_TRIGGERS


class Migration(migrations.Migration):
    dependencies = [
        ("yarrharr", "0008_feed_max_check_interval_feed_min_check_interval"),
    ]

    operations = [
        migrations.RunSQL(DROP_TRIGGERS, CREATE_TRIGGERS, elidable=True),
        migrations.AddField(
            model_name="feed",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feed",
            name="next_check",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.RunSQL(
            """
            UPDATE yarrharr_feed
            SET archived = (next_check IS NULL);
            """,
            None,
        ),
        migrations.RunSQL(CREATE_TRIGGERS, DROP_TRIGGERS, elidable=True),
    ]
