# Generated by Django 5.2.8 on 2025-12-03 03:26

from django.db import migrations, models
from ._0008_triggers import CREATE_TRIGGERS, DROP_TRIGGERS


class Migration(migrations.Migration):
    dependencies = [
        ("yarrharr", "0009_feed_archived_alter_feed_next_check"),
    ]

    operations = [
        migrations.RunSQL(DROP_TRIGGERS, CREATE_TRIGGERS, elidable=True),
        migrations.AddField(
            model_name="feed",
            name="checked",
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            """
            UPDATE yarrharr_feed
            SET checked = (NOT archived);
            """,
            None,
        ),
        migrations.RemoveField(
            model_name="feed",
            name="archived",
        ),
        migrations.RunSQL(CREATE_TRIGGERS, DROP_TRIGGERS, elidable=True),
    ]
