# Generated by Django 2.2.9 on 2020-01-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yarrharr", "0010_label_nonunique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="last_updated",
            new_name="last_changed",
        ),
    ]
