name: CI

on:
  push:
    branches: ["trunk"]
    tags: ["v*"]
  pull_request:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  just:
    name: "just ${{ matrix.recipe }}"

    strategy:
      matrix:
        recipe: ["test", "lint"]

    runs-on: ubuntu-24.04
    env:
      RUFF_OUTPUT_FORMAT: "github"

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - uses: ./.github/actions/setup-just
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: astral-sh/setup-uv@v7

      # Temporary hack: create files normally created by bin/compile-static.py
      # that are expected to exist by the manifest.json view test.
    - if: ${{ matrix.recipe == 'test' }}
      run: |
        mkdir yarrharr/static
        touch yarrharr/static/icon-xyz.{ico,png,svg}
        touch yarrharr/static/{normalize,main,fonts}-xyz.css
        touch yarrharr/static/{runtime,vendor,main}-xyz.js

    - run: just "$RECIPE"
      env:
        RECIPE: ${{ matrix.recipe }}

  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - uses: ./.github/actions/setup-just
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: astral-sh/setup-uv@v7

    - name: apt install
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-suggests --no-install-recommends inkscape scour

    - run: just _release

    - uses: actions/upload-artifact@v6
      with:
        name: dist
        path: dist/yarrharr-*.*
        if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]

    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:

    - uses: actions/download-artifact@v7
      with:
        name: dist
        path: dist/

    - run: |
        set -eux
        tag="${TAG_REF##*/}"
        version=${tag#v}
        gh release create "$tag" \
            --repo twm/yarrharr \
            --verify-tag \
            --title "Yarrharr $version" \
            --generate-notes \
            "dist/yarrharr-${version}-requirements.txt" \
            "dist/yarrharr-${version}.tar.gz" \
            "dist/yarrharr-${version}"*.whl
      env:
        GH_TOKEN: ${{ github.token }}
        TAG_REF: ${{ github.ref }}
