name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tox:
    name: "tox -e ${{ matrix.tox-env }}"

    strategy: 
      matrix:
        tox-env: ["test", "lint"]

    runs-on: ubuntu-20.04
    env:
      TOXENV: "${{ matrix.tox-env }}"

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3.1.2
      with:
        python-version: "3.9"

    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: "${{ runner.os }}-pip-${{ matrix.tox-env }}-${{ hashFiles('tox.ini') }}"
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.tox-env }}-
          ${{ runner.os }}-pip-

    - run: "python -m pip install tox"

      # Temporary hack: create files normally created by Webpack that are
      # expected to exist by the manifest.json view test.
    - run: |
        mkdir yarrharr/static
        touch yarrharr/static/{icon,logotype,lettertype}-xyz.{ico,png,svg}
        touch yarrharr/static/{normalize,main}-xyz.css
        touch yarrharr/static/{runtime,vendor,main}-xyz.js

    - run: "python -m tox"

  webpack:
    name: "make static"

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: apt install
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-suggests --no-install-recommends inkscape icoutils scour optipng node-less node-source-map

    - uses: actions/setup-python@v3.1.2
      with:
        python-version: "3.9"

    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: "${{ runner.os }}-pip-static-${{ hashFiles('tox.ini') }}"
        restore-keys: |
          ${{ runner.os }}-pip-static-
          ${{ runner.os }}-pip-

    - run: "python -m pip install tox"

    - run: "python -m tox -e static --notest"

    - run: "make static"
