name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tox:
    name: "tox -e ${{ matrix.tox-env }}"

    strategy: 
      matrix:
        tox-env: ["test", "lint"]

    runs-on: ubuntu-20.04
    env:
      TOXENV: "${{ matrix.tox-env }}"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - run: "python -m pip install tox"

    - run: "python -m tox"

  webpack:
    name: "make webpack-release"

    runs-on: ubuntu-20.04

    steps:
    - run: |
        set -exu
        sudo apt-get update
        sudo apt-get install inkscape icoutils scour optipng

    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - run: "python -m pip install tox"

    - run: "nvm install"

    - run: "npm install"

    - run: "make webpack-release"
