name: CI

on:
  push:
    branches: ["trunk"]
    tags: ["v*"]
  pull_request:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  just:
    name: "just ${{ matrix.recipe }}"

    strategy:
      matrix:
        recipe: ["test", "lint"]

    runs-on: ubuntu-24.04
    env:
      RUFF_OUTPUT_FORMAT: "github"
      # Disable caching in release workflows
      ENABLE_CACHE: ${{ !startsWith(github.ref, 'refs/tags/v' )}}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: ./.github/actions/setup-just
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: ${{ env.ENABLE_CACHE }}

      # Temporary hack: create files normally created by bin/compile-static.py
      # that are expected to exist by the manifest.json view test.
    - if: ${{ matrix.recipe == 'test' }}
      run: |
        mkdir yarrharr/static
        touch yarrharr/static/icon-xyz.{ico,png,svg}
        touch yarrharr/static/{normalize,main,fonts}-xyz.css
        touch yarrharr/static/{runtime,vendor,main}-xyz.js

    - run: just "$RECIPE"
      env:
        RECIPE: ${{ matrix.recipe }}
        UV_FROZEN: 1

  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: ./.github/actions/setup-just
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: ${{ env.ENABLE_CACHE }}

    - name: apt install
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-suggests --no-install-recommends inkscape scour

    - run: just _release
      env:
        UV_FROZEN: 1

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: dist
        path: dist/yarrharr-*.*
        if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]

    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: dist
        path: dist/

    - run: |
        set -eux
        tag="${TAG_REF##*/}"
        version=${tag#v}
        gh release create "$tag" \
            --repo twm/yarrharr \
            --verify-tag \
            --title "Yarrharr $version" \
            --generate-notes \
            "dist/yarrharr-${version}-requirements.txt" \
            "dist/yarrharr-${version}.tar.gz" \
            "dist/yarrharr-${version}"*.whl
      env:
        GH_TOKEN: ${{ github.token }}
        TAG_REF: ${{ github.ref }}
